name: Deploy custom artifacts to GitHub Pages

on:
  push:
    branches: ["main"]   # change to your branch if using a source branch
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # 1️⃣ Build your custom site/artifacts
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js (if using Node builds)
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Build site
        run: |
          # Example: create a simple HTML file
          mkdir -p public
          echo "<h1>Hello from GitHub Actions</h1>" > public/index.html
          echo "Built at $(date)" >> public/index.html

          # Optional: show files for debugging
          ls -R public

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public  # must match your output folder

  # 2️⃣ Deploy to GitHub Pages
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy artifact
        id: deployment
        uses: actions/deploy-pages@v4
